#!/bin/bash

module load Python-shared
module load R-3.3.0-sharedlib
module load bowtie2-2.3.2
module load stringtie-1.3.0
module load HISAT2-2.1.0

bsub -J RNASeqToolkit_TestData_3b -o RNASeqToolkit_TestData_3b.o_%J -e RNASeqToolkit_TestData_3b.e_%J -R "rusage[mem=5000] span[hosts=1]" -n 4 './run_test_bare'
